### ISSUE TITLE
conversion problem

### ISSUE THREAD

**Issue by ahua666** [TGlide/codeverter#1]
oh! Brother, when I try to convert a piece of JavaScript to TypeScript, the code he converts seems to be limited, only a small amount of code can be converted

**Comment by TGlide** [comment]
Yes, unfortunately it is a bit limited on the size allowed! It's a limitation of the OpenAI API, unfortunately 😕

**Comment by ahua666** [comment]
Too bad, is there any way to quickly convert a 20,000+ lines of JavaScript into TypeScript。😫😫😢

**Comment by TGlide** [comment]
Not that I know of 👀
