### ISSUE TITLE
My curious about the translate interface

### ISSUE THREAD

**Issue by Sinpo96** [TGlide/codeverter#2]
Hi, I am a frontend programmer and I would like to explore how to translate `React` to `Vue` in your project. 
Initially, I assumed that one would use `AST` or `Babel`. 
However, I noticed that you are only using a simple interface in your code. 
Would it be possible for you to explain what this interface does? Thank you.

https://github.com/TGlide/codeverter/blob/main/src/routes/api/generate/%2Bserver.ts#L24

**Comment by TGlide** [comment]
I'm just connecting to OpenAI's API, sending in a prompt to get the output back: https://platform.openai.com/docs/guides/completion

**Comment by Sinpo96** [comment]
OK，thanks

**Comment by TGlide** [comment]
> OK，thanks

NP!
