### ISSUE TITLE
Feature Request: Add option for users to choose GPT model

### ISSUE THREAD

**Issue by blackkspydo** [TGlide/codeverter#4]
# Problem Statement

Currently, the "codeverter" website does not provide users with the option to choose a specific GPT model for code conversion. The ability to select from various GPT models is essential, as each model may deliver different results based on its unique strengths and weaknesses. To improve user experience and meet diverse user requirements and effective costing, I propose integrating a GPT model selection feature.

# Proposed Solution

Introducing a dropdown menu or a dedicated selection panel would enable users to select their desired GPT model from a list of available options, such as GPT-3, GPT-3.5, or any other future GPT models that may be supported by the platform. The chosen GPT model would then be employed for code conversion.

**Comment by TGlide** [comment]
This is a good idea, I want to tackle this alongside some more advanced options e.g. customized options for each langauge and custom languages. Will create different issues for these
