### ISSUE TITLE
Feature Request: Synced Scroll for Side-by-Side Code Comparison

### ISSUE THREAD

**Issue by blackkspydo** [TGlide/codeverter#7]
# Problem Statement

Currently, the "codeverter" website does not offer a synced scroll feature for side-by-side code comparison. Users who wish to compare the original and converted code snippets may find it challenging to navigate through both sections simultaneously, particularly when dealing with long or complex code snippets. Implementing a synced scroll feature would improve the user experience by facilitating seamless comparison of the original and converted code.

# Proposed Solution

I propose adding a synced scroll functionality that allows users to scroll through both the original and converted code snippets simultaneously while maintaining their relative positions. This feature can be implemented using a checkbox or toggle button, enabling users to activate or deactivate synced scrolling based on their preference.

To achieve this functionality, consider using JavaScript to synchronize the scroll events of the two code sections, ensuring that they maintain their relative scroll positions.

**Comment by TGlide** [comment]
Hmm, I'm not sure if this would bring too much value IMO. What this does make me think of, is a diff comparison, similar to what we see in Github PRs, which could be interesting to see which pieces remained.

**Comment by TGlide** [comment]
Will close, as I don't think I will implement this. Thank you for the contribution!
